services:
  - type: web
    name: voyageo-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION_SECONDS
        value: "86400"
      - key: RAPIDAPI_KEY
        sync: false
      - key: BOOKING_API_HOST
        sync: false
      - key: BOOKING_API_BASE_URL
        sync: false
      - key: SNCF_API_KEY
        sync: false
      - key: SNCF_API_BASE_URL
        sync: false
      - key: FLIGHT_API_KEY
        sync: false
      - key: FLIGHT_API_BASE_URL
        sync: false
