services:
  - type: web
    name: voyageo-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION_SECONDS
        value: "86400"
      - key: TRAVELPAYOUTS_TOKEN
        sync: false
      - key: RAPIDAPI_KEY
        sync: false
      - key: BOOKING_API_HOST
        value: booking-com15.p.rapidapi.com
      - key: BOOKING_API_BASE_URL
        value: https://booking-com15.p.rapidapi.com
