services:
  - type: web
    name: voyageo-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION_SECONDS
        value: "86400"
      - key: TRAVELPAYOUTS_TOKEN
        sync: false
