spring.application.name=Voyageo
server.port=8080
spring.jpa.open-in-view=false
spring.datasource.url=jdbc:h2:file:./data/voyageo;MODE=PostgreSQL;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Sécurité JWT
security.jwt.secret=${JWT_SECRET:change-me-super-secret-32-bytes-minimum}
security.jwt.expiration-seconds=${JWT_EXPIRATION_SECONDS:86400}

# Providers externes (activables via env)
providers.booking.enabled=${BOOKING_API_ENABLED:false}
providers.booking.base-url=${BOOKING_API_BASE_URL:https://booking-com15.p.rapidapi.com/api/v1}
providers.booking.host=${BOOKING_API_HOST:booking-com15.p.rapidapi.com}
providers.booking.api-key=${RAPIDAPI_KEY:}

providers.flight.enabled=${FLIGHT_API_ENABLED:false}
providers.flight.base-url=${FLIGHT_API_BASE_URL:https://api.tequila.kiwi.com}
providers.flight.api-key=${FLIGHT_API_KEY:}

providers.sncf.enabled=${SNCF_API_ENABLED:false}
providers.sncf.base-url=${SNCF_API_BASE_URL:https://api.sncf.com/v1}
providers.sncf.api-key=${SNCF_API_KEY:}
